@startuml
class NoFileWithThisClassNameFoundException {
}
class CompilationFailedException {
}
class ScriptExecutionException {
}
class ActionScriptExecutionException {
}
class ConditionScriptExecutionException {
}
class GetScriptPathFromFolderException {
}
class CreateStringFromCsFileException {
}
class NoClassFoundInScriptFileException {
}
class MoreThanOneClassFoundInScriptException {
}
class ValidationBeforeCompilationException {
}
class ClassNameOrBaseNameNullException {
}
class ForbiddenNamespaceException {
    <<new>> - Message : string
    + ForbiddenNamespaceException(message:string)
}
class ScriptTimeoutException {
    <<new>> - Message : string
    + ScriptTimeoutException(message:string)
}
Exception <|-- NoFileWithThisClassNameFoundException
Exception <|-- CompilationFailedException
Exception <|-- ScriptExecutionException
Exception <|-- ActionScriptExecutionException
Exception <|-- ConditionScriptExecutionException
Exception <|-- GetScriptPathFromFolderException
Exception <|-- CreateStringFromCsFileException
Exception <|-- NoClassFoundInScriptFileException
Exception <|-- MoreThanOneClassFoundInScriptException
Exception <|-- ValidationBeforeCompilationException
Exception <|-- ClassNameOrBaseNameNullException
Exception <|-- ForbiddenNamespaceException
Exception <|-- ScriptTimeoutException
@enduml
