// <auto-generated />
using System;
// using EFModeling.EntityProperties.FluentAPI.Required;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorUI.Migrations
{
    [DbContext(typeof(ScriptDbContext))]
    [Migration("20260317103218_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ember.Scripting.CustomerScript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("MinApiVersion")
                        .HasColumnType("integer")
                        .HasColumnName("min_api_version");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ScriptName")
                        .HasColumnType("text")
                        .HasColumnName("script_name");

                    b.Property<string>("ScriptType")
                        .HasColumnType("text")
                        .HasColumnName("script_type");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_code");

                    b.HasKey("Id");

                    b.ToTable("customer_scripts");
                });

            modelBuilder.Entity("Ember.Scripting.EmberInstance", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("EmberVersion")
                        .HasColumnType("text")
                        .HasColumnName("ember_version");

                    b.Property<string>("Hostname")
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<string>("InstanceName")
                        .HasColumnType("text")
                        .HasColumnName("instance_name");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat");

                    b.Property<int>("SdkVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sdk_version");

                    b.HasKey("InstanceId");

                    b.ToTable("ember_instances");
                });

            modelBuilder.Entity("Ember.Scripting.ScriptCompiledCache", b =>
                {
                    b.Property<Guid>("ScriptId")
                        .HasColumnType("uuid")
                        .HasColumnName("script_id");

                    b.Property<int>("ApiVersion")
                        .HasColumnType("integer")
                        .HasColumnName("api_version");

                    b.Property<byte[]>("AssemblyBytes")
                        .HasColumnType("bytea")
                        .HasColumnName("assembly_bytes");

                    b.Property<DateTime>("CompilationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("compilation_date");

                    b.Property<string>("CompilationErrors")
                        .HasColumnType("text")
                        .HasColumnName("copilation_errors");

                    b.Property<bool>("CompilationSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("compilation_success");

                    b.Property<string>("OldSourceCode")
                        .HasColumnType("text")
                        .HasColumnName("old_source_code");

                    b.HasKey("ScriptId", "ApiVersion");

                    b.ToTable("script_compiled_cache");
                });

            modelBuilder.Entity("Ember.Scripting.ScriptCompiledCache", b =>
                {
                    b.HasOne("Ember.Scripting.CustomerScript", "CustomerScript")
                        .WithMany("CompiledCaches")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerScript");
                });

            modelBuilder.Entity("Ember.Scripting.CustomerScript", b =>
                {
                    b.Navigation("CompiledCaches");
                });
#pragma warning restore 612, 618
        }
    }
}
