@startuml
class ScriptExecutor {
    - <<readonly>> {static} ScriptTimeout : int = 5000
    - <<readonly>> Logger : ILogger<ScriptExecutor>
    + ScriptExecutor(logger:ILogger<ScriptExecutor>)
    + RunScriptExecution(compiledScript:byte[], genContext:GeneratorContext) : T
    + RunConditionScript(type:Type, scriptInstance:object, genContext:GeneratorContext) : bool
    + RunActionScript(type:Type, scriptInstance:object, genContext:GeneratorContext) : ActionResultBaseClass
}
@enduml
