@startuml
class ScriptCompiler {
    - <<readonly>> References2 : MetadataReference[]? = null
    - <<readonly>> Logger : ILogger<ScriptCompiler>
    + ScriptCompiler(references2:MetadataReference[], logger:ILogger<ScriptCompiler>)
    + RunCompilation(script:string, references:MetadataReference[]?, apiVersion:int, metaData:(string className, string baseTypeName, int versionInt)?) : byte[]
    + BasicValidationBeforeCompiling(script:string) : (string className, string baseTypeName, int versionInt)
    - ValidateNamespaceUsage(tree:SyntaxTree, model:SemanticModel) : void
    + IsTheSameTree(script1:string, script2:string) : bool
    + GetReferencesForVersion(version:int, customDlls:string[]?, loadCurrentRT:bool) : MetadataReference[]
}
@enduml
