@startuml
class ScriptCompiler {
    - <<readonly>> References2 : List<MetadataReference>? = null
    - <<readonly>> Logger : ILogger<ScriptCompiler>
    - <<readonly>> StandardRefrencesForAllScripts : List<MetadataReference>
    + ScriptCompiler(references2:List<MetadataReference>, logger:ILogger<ScriptCompiler>)
    + RunCompilation(script:string, apiVersion:int?, metaData:(string className, string baseTypeName, int versionInt)?) : byte[]
    + GetBaseType(script:string) : INamedTypeSymbol
    + BasicValidationBeforeCompiling(script:string) : (string className, string baseTypeName, int versionInt)
    - ValidateNamespaceUsage(tree:SyntaxTree, model:SemanticModel) : void
    + IsTheSameTree(script1:string, script2:string) : bool
    + GetReferencesForOldVersion(version:int, customDlls:List<string>?, loadCurrentRT:bool) : List<MetadataReference>
}
@enduml
