@startuml
interface PatientInterface {
    PatientId : string <<get>>
    FirstName : string <<get>>
    LastName : string <<get>>
    DateOfBirth : DateTime? <<get>>
    Gender : string <<get>>
    Age : int <<get>>
    GetCustomField(fieldName:string) : string?
}
class Patient {
    + PatientId : string <<get>>
    + FirstName : string <<get>>
    + LastName : string <<get>>
    + DateOfBirth : DateTime? <<get>>
    + Gender : string <<get>>
    - _customFields : Dictionary<string, string>
    + Patient(id:string, first:string, last:string, dob:DateTime?, gender:string)
    + Age : int <<get>>
    + GetCustomField(fieldName:string) : string?
    + SetCustomField(key:string, value:string) : void
}
PatientInterface <|-- Patient
@enduml
