@startuml
interface IGeneratorBaseInterface {
}
abstract class GeneratorContext {
    + {abstract} Downgrade() : GeneratorContext
    + {abstract} CreateUsingData(data:DataBaseClass) : GeneratorContext
}
abstract class DataBaseClass {
}
@enduml
