@startuml
class DbHelper {
    - <<readonly>> References : List<MetadataReference>
    - <<readonly>> Compiler : ScriptCompiler
    - <<readonly>> Logger : ILogger<DbHelper>
    - <<readonly>> RecentApiVersion : int
    + DbHelper(compiler:ScriptCompiler, references:List<MetadataReference>, logger:ILogger<DbHelper>, recentApiVersion:int)
    + <<async>> EnsureDeletedCreated() : Task
    + <<async>> GetAllCustomerScripts(includeCaches:bool, filters:CustomerScriptFilter?) : Task<List<CustomerScript>>
    + <<async>> GetAllCompiledScriptCaches(includeScripts:bool) : Task<List<ScriptCompiledCache>>
    + GetRecentApiVersion() : int
    + <<async>> ClearScriptCache(scriptId:Guid) : Task
    + <<async>> RecompileScript(scriptId:Guid, deleteAlso:bool) : Task
    + <<async>> AutomaticCompilationOnVersionUpdate(currentApiVersion:int) : Task
    + <<async>> CreateAndInsertCustomerScript(scriptString:string, randomGUID:Guid, createdBy:string, oldApiV:int?, createdAt:DateTime?, alsoCompAndSave:bool, checkForDuplicates:bool) : Task<CustomerScript>
    + <<async>> CreateAndInsertCompiledCache(script:CustomerScript, apiV:int?) : Task
    + <<async>> DeleteCustomerScript(id:Guid) : Task
    + <<async>> DeleteScriptCache(id:Guid, ApiVersion:int) : Task
    + <<async>> UpdateScript(scriptId:Guid, newSourceCode:string, userName:string?, apiVersion:int?) : Task
    + <<async>> InsertScriptCompiledCache(scriptCompiledCache:ScriptCompiledCache) : Task
    + <<async>> GetCompiledScripCache(id:Guid, ApiVersion:int) : Task<ScriptCompiledCache>
    + <<async>> GetCustomerScript(id:Guid, includeCaches:bool) : Task<CustomerScript>
    + <<async>> CompileAllStoredScripts(currentApiVersion:int) : Task
    + <<async>> SaveScriptWithoutCompiling(id:Guid, sourceCode:string, userName:string?) : Task
    + <<async>> DeleteAllCachedScripts() : Task
    + <<async>> IsDuplicateScript(script:CustomerScript) : Task<bool>
    + <<async>> DetectDuplicates() : Task<(List<Guid> scriptGUIDs, Dictionary<Guid, int> cacheGUIDs)>
    + <<async>> GetActiveApiVersions() : Task<List<int>>
    + <<async>> GetMostRecentApiVersionInDb() : Task<int>
    + <<async>> RemoveDuplicates() : Task
    + <<async>> HealthCheck() : Task
    + <<async>> GetCachesForEachApiVersion() : Task<Dictionary<int, List<ScriptCompiledCache>>>
}
@enduml
