@startuml
class DbHelper {
    - <<readonly>> References : MetadataReference[]
    - <<readonly>> Compiler : ScriptCompiler
    - <<readonly>> Logger : ILogger<DbHelper>
    + DbHelper(compiler:ScriptCompiler, references:MetadataReference[], logger:ILogger<DbHelper>)
    + <<async>> EnsureDeletedCreated() : Task
    + <<async>> GetAllCustomerScripts(includeCaches:bool, filters:CustomerScriptFilter?) : Task<List<CustomerScript>>
    + <<async>> GetAllCompiledScriptCaches() : Task<List<ScriptCompiledCache>>
    + <<async>> GetRecentApiVersion() : Task<int>
    + <<async>> ClearScriptCache(scriptId:Guid) : Task
    + <<async>> RecompileScript(scriptId:Guid, deleteAlso:bool) : Task
    + <<async>> AutomaticCompilationOnVersionUpdate(currentApiVersion:int) : Task
    + <<async>> CreateAndInsertCustomerScript(scriptString:string, randomGUID:Guid, createdBy:string, oldApiV:int, createdAt:DateTime?) : Task<CustomerScript>
    + <<async>> CreateAndInsertCompiledCache(script:CustomerScript, oldApiV:int) : Task
    + <<async>> DeleteCustomerScript(id:Guid) : Task
    + <<async>> DeleteScriptCache(id:Guid, ApiVersion:int) : Task
    + <<async>> UpdateCustomerScript(customerScript:CustomerScript) : Task
    + <<async>> InsertScriptCompiledCache(scriptCompiledCache:ScriptCompiledCache) : Task
    + <<async>> GetCompiledScripCache(id:Guid, ApiVersion:int) : Task<ScriptCompiledCache>
    + <<async>> GetCustomerScript(id:Guid, includeCaches:bool) : Task<CustomerScript>
    + <<async>> CompileAllStoredScripts(currentApiVersion:int) : Task
    + <<async>> DeleteAllCachedScripts() : Task
    + <<async>> IsDuplicateScript(script:CustomerScript) : Task<bool>
    + <<async>> DetectDuplicates() : Task<(List<Guid> scriptGUIDs, Dictionary<Guid, int> cacheGUIDs)>
    + <<async>> GetActiveApiVersions() : Task<List<int>>
    + <<async>> RemoveDuplicates() : Task
    + <<async>> HealthCheck() : Task
}
@enduml
