@startuml
class EmberInstance {
    + InstanceId : Guid <<get>> <<set>>
    + InstanceName : string? <<get>> <<set>>
    + EmberVersion : string? <<get>> <<set>>
    + SdkVersion : int <<get>> <<set>>
    + LastHeartbeat : DateTime <<get>> <<set>>
    + Hostname : string? <<get>> <<set>>
    + <<override>> ToString() : string
}
@enduml
