@startuml
class ScriptCompiledCache {
    + ScriptId : Guid <<get>> <<set>>
    + ApiVersion : int <<get>> <<set>>
    + AssemblyBytes : byte[]? <<get>> <<set>>
    + CompilationDate : DateTime <<get>> <<set>>
    + CompilationSuccess : bool <<get>> <<set>>
    + CompilationErrors : string? <<get>> <<set>>
    + OldSourceCode : string? <<get>> <<set>>
    + CustomerScript : CustomerScript? <<get>> <<set>>
    + <<override>> ToString() : string
    + ToStringBetter() : string
}
@enduml
