@startuml
class ActionResult {
    + IsSuccess : bool <<get>>
    + Message : string <<get>>
    + ErrorCode : string <<get>>
    # ActionResult(isSuccess:bool, message:string, errorCode:string?)
    + {static} Success(message:string) : ActionResult
    + {static} Failure(message:string, errorCode:string) : ActionResult
    + <<override>> ToString() : string
    + <<override>> Upgrade(actionResult:ActionResultBaseClass) : ActionResultBaseClass
}
class ActionResult {
    + LoggedActions : List<string> <<get>>
    - ActionResult(isSuccess:bool, message:string, errorCode:string?, loggedActions:List<string>)
    + <<new>> {static} Success(message:string) : ActionResult
    + {static} Failure(message:string, loggedActions:List<string>, errorCode:string) : ActionResult
    + AppendLoggedActions(action:string) : void
    + GetLoggedActions() : List<string>
    + {static} UpgradeV1(actionResult:ActionResultV1.ActionResult, loggedActions:List<string>) : ActionResult
    + <<override>> Upgrade(actionResult:ActionResultBaseClass) : ActionResultBaseClass
}
class ActionResult {
    + FailedOrNot : bool <<get>>
    + Message : string <<get>>
    # ActionResult(failedOrNot:bool, message:string)
    + {static} Success(message:string) : ActionResult
    + {static} Failure(message:string) : ActionResult
    + <<override>> ToString() : string
    + {static} UpgradeV2(actionResult:ActionResultV2.ActionResult) : ActionResult
    + <<override>> Upgrade(actionResult:ActionResultBaseClass) : ActionResultBaseClass
}
ActionResultBaseClass <|-- ActionResult
ActionResultBaseClass <|-- ActionResult
@enduml
