@startuml
class ActionResult {
    + IsSuccess : bool <<get>>
    + Message : string <<get>>
    + ErrorCode : string <<get>>
    # ActionResult(isSuccess:bool, message:string, errorCode:string?)
    + {static} Success(message:string) : ActionResult
    + {static} Failure(message:string, errorCode:string) : ActionResult
    + <<override>> ToString() : string
}
class ActionResultV2 {
    + LoggedActions : List<string> <<get>>
    - ActionResultV2(isSuccess:bool, message:string, errorCode:string?, loggedActions:List<string>)
    + <<new>> {static} Success(message:string) : ActionResultV2
    + {static} Failure(message:string, loggedActions:List<string>, errorCode:string) : ActionResultV2
    + AppendLoggedActions(action:string) : void
    + GetLoggedActions() : List<string>
    + {static} UpgradeV1(actionResult:ActionResult, loggedActions:List<string>) : ActionResultV2
}
class ActionResultV3NoInheritance {
    + FailedOrNot : bool <<get>>
    + Message : string <<get>>
    # ActionResultV3NoInheritance(failedOrNot:bool, message:string)
    + {static} Success(message:string) : ActionResultV3NoInheritance
    + {static} Failure(message:string) : ActionResultV3NoInheritance
    + <<override>> ToString() : string
    + {static} UpgradeV2(actionResult:ActionResultV2) : ActionResultV3NoInheritance
}
ActionResultBaseClass <|-- ActionResult
ActionResult <|-- ActionResultV2
ActionResultBaseClass <|-- ActionResultV3NoInheritance
@enduml
