@startuml
interface "IGeneratorConditionScript`1"<TContext> {
    EvaluateAsync(context:TContext) : Task<bool>
    EvaluateAsync(context:IGeneratorBaseInterface) : Task<bool>
}
interface "IGeneratorActionScript`1"<TContext> {
    ExecuteAsync(context:TContext) : Task<ActionResultBaseClass>
    ExecuteAsync(context:IGeneratorBaseInterface) : Task<ActionResultBaseClass>
}
interface "IGeneratorActionScript`2"<TContext,TActionResult> {
    ExecuteAsync(context:TContext) : Task<TActionResult>
    <<async>> ExecuteAsync(context:IGeneratorBaseInterface) : Task<ActionResultBaseClass>
}
interface IGeneratorActionScriptV2 {
    ExecuteAsync(context:IGeneratorContext_V2) : Task<ActionResultV2>
    ExecuteAsync(context:IGeneratorBaseInterface) : Task<ActionResultBaseClass>
}
interface IGeneratorActionScriptV3 {
    ExecuteAsync(context:IGeneratorContext_V3) : Task<ActionResultV3NoInheritance>
    ExecuteAsync(context:IGeneratorBaseInterface) : Task<ActionResultBaseClass>
}
interface IGeneratorActionScriptV4Vaccine {
    ExecuteAsync(context:IGeneratorContextNoInheritance_V4) : Task<ActionResultV3NoInheritance>
    ExecuteAsync(context:IGeneratorBaseInterface) : Task<ActionResultBaseClass>
}
IGeneratorConditionScript <|-- "IGeneratorConditionScript`1"
IGeneratorActionScript <|-- "IGeneratorActionScript`1"
IGeneratorActionScript <|-- "IGeneratorActionScript`2"
IGeneratorActionScript <|-- IGeneratorActionScriptV2
IGeneratorActionScript <|-- IGeneratorActionScriptV3
IGeneratorActionScript <|-- IGeneratorActionScriptV4Vaccine
@enduml
