@startuml
interface "IGeneratorConditionScript`1"<TContext> {
    EvaluateAsync(context:TContext) : Task<bool>
    EvaluateAsync(context:IGeneratorBaseInterface) : Task<bool>
}
interface "IGeneratorActionScript`1"<TContext> {
    ExecuteAsync(context:TContext) : Task<ActionResultBaseClass>
    ExecuteAsync(context:IGeneratorBaseInterface) : Task<ActionResultBaseClass>
}
interface "IGeneratorActionScript`2"<TContext,TActionResult> {
    ExecuteAsync(context:TContext) : Task<TActionResult>
    <<async>> ExecuteAsync(context:IGeneratorBaseInterface) : Task<ActionResultBaseClass>
}
interface IGeneratorActionScript {
    ExecuteAsync(context:IGeneratorContext_V3.IGeneratorContext) : Task<ActionResultV2.ActionResult>
    ExecuteAsync(context:IGeneratorBaseInterface) : Task<ActionResultBaseClass>
}
interface IGeneratorActionScript {
    ExecuteAsync(context:IGeneratorContext_V4.IGeneratorContext) : Task<ActionResultV3.ActionResult>
    ExecuteAsync(context:IGeneratorBaseInterface) : Task<ActionResultBaseClass>
}
interface IGeneratorActionScript {
    ExecuteAsync(context:IGeneratorContextNoInheritance_V5.IGeneratorContext) : Task<ActionResultV3.ActionResult>
    ExecuteAsync(context:IGeneratorBaseInterface) : Task<ActionResultBaseClass>
}
IGeneratorConditionScript <|-- "IGeneratorConditionScript`1"
IGeneratorActionScript <|-- "IGeneratorActionScript`1"
IGeneratorActionScript <|-- "IGeneratorActionScript`2"
@enduml
