global using RecentActionResult = ActionResultV3.ActionResult;
global using RecentIGeneratorContext = IGeneratorContextNoInheritance_V5.IGeneratorContext;
global using RecentGeneratorContext = GeneratorContextNoInherVaccineV5.GeneratorContext;
// global using RecentIGeneratorConditionScript = GeneratorScriptsGenericSimple.IGeneratorConditionScript<IGeneratorReadOnlyContextV1.IGeneratorContext>;
global using RecentIGeneratorConditionScript = GeneratorScriptsGenericSimple.IGeneratorConditionScript<IGeneratorContextNoInheritance_V5.IGeneratorContext>;
global using RecentIGeneratorActionScript = GeneratorScriptsV4.IGeneratorActionScript;
global using RecentDataClass = DataV2.DataV2;
global using RecentContextFactory = GeneratorContextNoInherVaccineV5;
// global using ActiveMultiersionActionScript = Mu/
