// // Generated By AI
public class ActionResult
{
    public bool IsSuccess { get; private set; }
    public string Message { get; private set; }
    public string ErrorCode { get; private set; }

    // Constructor is private to enforce using factory methods
    private ActionResult(bool isSuccess, string message, string errorCode = null)
    {
        IsSuccess = isSuccess;
        Message = message;
        ErrorCode = errorCode;
    }

    // Factory method for success (Matches your script usage)
    public static ActionResult Success(string message)
    {
        return new ActionResult(true, message);
    }

    // Factory method for failure (Good practice to have)
    public static ActionResult Failure(string message, string errorCode = "GENERIC_ERROR")
    {
        return new ActionResult(false, message, errorCode);
    }

    // Override ToString for easier debugging
    public override string ToString()
    {
        return IsSuccess ? $"[Success] {Message}" : $"[Error: {ErrorCode}] {Message}";
    }
}

