@startuml
interface IScriptManagerExtended {
    CreateScript(sourceCode:string, userName:string, apiVersion:int?, createdAt:DateTime?, checkForDuplicates:bool) : Task<Guid>
    UpdateScript(scriptId:Guid, newSourceCode:string, userName:string?, apiVersion:int?) : Task
    DeleteScript(scriptId:Guid) : Task
    GetScript(scriptId:Guid, includeCaches:bool) : Task<CustomerScript>
}
class CustomerScriptFilter {
    + ScriptName : string?
    + ScriptType : string?
    + SourceCode : string?
    + MinApiVersion : int?
    + CreatedAt : DateTime?
    + ModifiedAt : DateTime?
    + CreatedBy : string?
    + CustomerScriptFilter(scriptName:string?, scriptType:string?, sourceCode:string?, minApiVersion:int?, createdAt:DateTime?, modifiedAt:DateTime?, createdBy:string?)
}
IScriptManager <|-- IScriptManagerExtended
@enduml
