@startuml
!include .\\.\sandbox\src\EmberMethods.puml
!include .\\.\sandbox\src\LoggerForScripting.puml
!include .\\.\sandbox\src\InternalClassesForTesting\HelperServices.puml
!include .\\.\sandbox\src\InternalClassesForTesting\LabOrder.puml
!include .\\.\sandbox\src\InternalClassesForTesting\MockData.puml
!include .\\.\sandbox\src\InternalClassesForTesting\Patient.puml
!include .\\.\sandbox\src\InternalClassesForTesting\Test.puml
!include .\\.\sandbox\src\InternalClassesForTesting\Vaccine.puml
!include .\\.\sandbox\src\ScriptingFramework\ActionResult.puml
!include .\\.\sandbox\src\ScriptingFramework\ContextFactory.puml
!include .\\.\sandbox\src\ScriptingFramework\GeneratorContexts.puml
!include .\\.\sandbox\src\ScriptingFramework\GeneratorScripts.puml
!include .\\.\sandbox\src\Scripts\ActionScripts\AddPediatricTestsV1.puml
!include .\\.\sandbox\src\Scripts\ActionScripts\AddPediatricTestsV2.puml
!include .\\.\sandbox\src\Scripts\ActionScripts\AddPediatricTestsV3.puml
!include .\\.\sandbox\src\Scripts\ActionScripts\VaccineScript.puml
!include .\\.\sandbox\src\Scripts\ConditionScripts\PediatricCondition.puml
@enduml
